### PR TITLE
Syntax and incomplete `case` updates

### PR DESCRIPTION
**Pull request by randomer**

### CODE REVIEW

**Comment by eeue56** [comment]
Looks good, though the default case for `unpackMaybeSize` should return an impossible size on `Nothing`, using `(-1, -1)` instead of `(0, 0)`

**Comment by randomer** [comment]
Good point. Updated

**Comment by eeue56** [comment]
Merged and published, thanks!

**Comment by randomer** [comment]
Awesome! :+1: :tada:

**Pull request merged**
