### PR TITLE
upgrade elm-test to 3.1.1

### PR DESCRIPTION
**Pull request by mbylstra**
also:
- remove trailing whitespace from tests
- remove unused import

### CODE REVIEW

**Comment by mbylstra** [comment]
Hi,

elm-package wouldn't let me install elm-flat-matrix into my project as I was using a newer incompatible version of elm-test. I'm not sure of a way to include multiple versions of a package at once, so I figured  it wouldn't hurt to upgrade elm-test in elm-flat-matrix. I'm afraid the diff is really messy, as I'm using Atom and it seems to automatically strip all the trailing whitespace, and I'm not sure how to turn this feature off. There's no huge rush on merging this. FYI I'll be using elm-flat-matrix for a matrix step sequencer.

cheers,
Michael.

**Comment by mbylstra** [comment]
I've run the tests successfully using elm-reactor (and the elementRunner). I'm not sure why the Travis test is failing.

**Comment by eeue56** [comment]
Thanks for this! I had meant to upgrade it but didn't get around to it. I'm merge now

**Comment by mbylstra** [comment]
Awesome. Thanks!

**Comment by eeue56** [comment]
@mbylstra published as 2.0.4

**Pull request merged**
